version: "3.8"
services:
  test-app:
    container_name: atacado-hub-test-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - test-db
    env_file:
      - .env
    command: >
      sh -c "
      npm install &&
      npm run test &&
      npm run test:e2e &&
      npm run test:cov
      "
    networks:
      - atacado-hub-network

  test-db:
    image: postgres:14-alpine
    container_name: atacado-hub-test-db
    ports:
      - "5433:5432" # Porta local diferente para n√£o conflitar com o ambiente normal
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: atacado-hub
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - atacado-hub-network
   
volumes:
  postgres-test-data:
  
networks:
  atacado-hub-network:
    driver: bridge
